# Generated by Django 5.2.8 on 2025-11-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('your_name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('image_link', models.URLField(blank=True, null=True)),
                ('Content', models.TextField()),
                ('Tags', models.CharField(help_text='Comma-separated tags', max_length=250)),
            ],
        ),
    ]
